before_install:
  - psql --version
  - sudo service postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - sudo apt-get update -qq
  - sudo apt-get -y install bc libpam-dev libedit-dev
  - git clone https://github.com/postgres/postgres.git postgres-dev
  - cd postgres-dev
  - if [ $PGVERSION = 12 ] ; then git checkout -b REL_12_STABLE origin/REL_12_STABLE; fi
  - if [ $PGVERSION = 11 ] ; then git checkout -b REL_11_STABLE origin/REL_11_STABLE; fi
  - if [ $PGVERSION = 10 ] ; then git checkout -b REL_10_STABLE origin/REL_10_STABLE; fi
  - if [ $PGVERSION = 9.6 ] ; then git checkout -b REL9_6_STABLE origin/REL9_6_STABLE; fi
  - if [ $PGVERSION = 9.5 ] ; then git checkout -b REL9_5_STABLE origin/REL9_5_STABLE; fi
  - if [ $PGVERSION = 9.4 ] ; then git checkout -b REL9_4_STABLE origin/REL9_4_STABLE; fi
  - if [ $PGVERSION = 9.3 ] ; then git checkout -b REL9_3_STABLE origin/REL9_3_STABLE; fi
  - export POSTGRES_HOME=/home/travis/build/ossc-db/pg_bulkload/pgsql/$PGVERSION
  - ./configure --prefix=$POSTGRES_HOME
  - make -j 2
  - make install
  - echo 'export PATH=$PATH:$POSTGRES_HOME/bin' >> ~/.bashrc
  - export PATH=$PATH:$POSTGRES_HOME/bin
  - echo 'export PGDATA=/home/travis/build/ossc-db/pg_bulkload/pg_data/$PGVERSION' >> ~/.bashrc
  - export PGDATA=/home/travis/build/ossc-db/pg_bulkload/pg_data/$PGVERSION
  - cd /home/travis/build/ossc-db/pg_bulkload
  - mkdir -p $PGDATA
  - initdb --no-locale -D $PGDATA
  - sudo echo "local   all         postgres                          trust" > $PGDATA/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> $PGDATA/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> $PGDATA/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> $PGDATA/pg_hba.conf
  - sudo echo "logging_collector = on" >> $PGDATA/postgresql.conf
  - pg_ctl -V
  - pg_ctl -D $PGDATA start

before_script:
  - cd /home/travis/build/ossc-db/pg_bulkload
  - git clone https://github.com/ossc-db/pg_bulkload.git pg_bulkload
  - cd pg_bulkload && git describe --alway
  - make
  - make install

env:
  matrix:
    - PGVERSION=12
    - PGVERSION=11
    - PGVERSION=10
    - PGVERSION=9.6
    - PGVERSION=9.5
    - PGVERSION=9.4
    - PGVERSION=9.3

language: cpp
compiler:
#  - clang
  - gcc

script: make installcheck

after_script:
  - cat /home/travis/build/ossc-db/pg_bulkload/pg_bulkload/bin/regression.diffs
