before_install:
  - psql --version
  - sudo service postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo apt-get update -qq
  - sudo apt-get -y install bc libpam-dev libedit-dev
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION postgresql-contrib-$PGVERSION
  - sudo apt-cache policy libpq5
  - sudo apt-cache policy libpq-dev
  - if [ $PGVERSION = 9.3 ] ; then sudo apt-get -y --force-yes install libpq5=9.3.10-1.pgdg12.4+1 libpq-dev=9.3.10-1.pgdg12.4+1 ; fi
  - if [ $PGVERSION = 9.2 ] ; then sudo apt-get -y --force-yes install libpq5=9.2.14-1.pgdg12.4+1 libpq-dev=9.2.14-1.pgdg12.4+1 ; fi
  - if [ $PGVERSION = 9.1 ] ; then sudo apt-get -y --force-yes install libpq5=9.1.19-1.pgdg12.4+1 libpq-dev=9.1.19-1.pgdg12.4+1 ; fi
  - if [ $PGVERSION = 9.0 ] ; then sudo apt-get -y --force-yes install libpq5=9.0.23-1.pgdg12.4+1 libpq-dev=9.0.23-1.pgdg12.4+1 ; fi
  - if [ $PGVERSION = 8.4 ] ; then sudo apt-get -y --force-yes install libpq5=8.4.22-1.pgdg12.4+1 libpq-dev=8.4.22-1.pgdg12.4+1 ; fi
  - sudo service postgresql stop
  - echo 'export PATH=$PATH:/usr/lib/postgresql/$PGVERSION/bin' >> ~/.bashrc
  - export PATH=$PATH:/usr/lib/postgresql/$PGVERSION/bin
  - echo 'export PGDATA=/home/travis/build/ossc-db/pg_bulkload/pg_data/$PGVERSION' >> ~/.bashrc
  - export PGDATA=/home/travis/build/ossc-db/pg_bulkload/pg_data/$PGVERSION
  - mkdir pg_data
  - initdb --no-locale -D pg_data/$PGVERSION
  - sudo chmod 777 /var/run/postgresql
  - sudo echo "local   all         postgres                          trust" > $PGDATA/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> $PGDATA/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> $PGDATA/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> $PGDATA/pg_hba.conf
  - sudo echo "logging_collector = on" >> $PGDATA/postgresql.conf
  - pg_ctl -V
  - pg_ctl -D $PGDATA start

before_script:
  - git clone https://github.com/ossc-db/pg_bulkload.git pg_bulkload
  - cd pg_bulkload && git describe --alway
  - git checkout -b VERSION3_1_STABLE origin/VERSION3_1_STABLE
  - make
  - sudo make install

env:
  matrix:
    - PGVERSION=9.4
    - PGVERSION=9.3
    - PGVERSION=9.2
    - PGVERSION=9.1
    - PGVERSION=9.0
    - PGVERSION=8.4

language: cpp
compiler:
#  - clang
  - gcc

script: make installcheck

after_script:
  - cat /home/travis/build/ossc-db/pg_bulkload/pg_bulkload/bin/regression.diffs
